kumuluzee:
  name: catalog
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/catalogDS
    connection-url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: admin
    max-pool-size: 20