apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-management
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: catalog-management
    spec:
      containers:
      - name: catalog-management
        image: rso9/catalog-management:0.2.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: rso9
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: CONNECTION_URL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: DB_PASS
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: catalog-management
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: catalog-management
  type: LoadBalancer
